# /*
#  * @Author: hongqianhui hongqianhui@bytedance.com
#  * @Date: 2022-05-07 21:30:26
#  * @LastEditors: hongqianhui hongqianhui@bytedance.com
#  * @LastEditTime: 2022-05-07 21:30:27
#  * @FilePath: /c_pro/ffmpeg_demos/vin_vout/Makefile
#  * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
#  */
all:
	gcc main.c ../util.c -o main `pkg-config --cflags --libs libavcodec,libavformat`